Find successful list of prelink and postlink O2 passes.
This commit introduces try_passes.py script, which uses a divide-and-conquer approach to
identify a list of passes that successfully build yklua and execute its tests n times.
Additionally, we added two new arguments to yk-config that allow for the overriding of cflags and
ldflags with custom prelink and postlink flags.

diff --git a/bin/yk-config b/bin/yk-config
--- a/bin/yk-config
+++ b/bin/yk-config
@@ -10,20 +10,21 @@ if [ ! -d "${DIR}/../ykrt" ]; then
     exit 1
 fi
 
-# The link-time optimisations that we can tolerate.
+# The post-link time optimisations that we can tolerate.
 #
 # FIXME: Once we know what breaks us, allow the user to use the regular -O0,
 # -O1, -O2, etc. clang flags like normal.
-LINKTIME_PASSES=instcombine
+POSTLINK_PASSES_STR=instcombine
 
 OUTPUT=""
 
 usage() {
     echo "Generate C compiler flags for building against the yk JIT.\n"
     echo "Usage:"
-    echo "    yk-config <mode> <--cc|--cxx|--ar|--ranlib|--cppflags|--cflags|--ldflags>\n"
+    echo "    yk-config <mode> [--prelink-pipeline <passes>] [--postlink-pipeline <passes>] <--cc|--cxx|--ar|--ranlib|--cppflags|--cflags|--ldflags>\n"
     echo "    Where <mode> is either 'debug' or 'release'."
 }
+
 
 handle_arg() {
     mode=$1
@@ -41,6 +42,26 @@ handle_arg() {
         --cxx) OUTPUT="${ykllvm_bin_dir}/clang++" ;;
         --ar) OUTPUT="${ykllvm_bin_dir}/llvm-ar" ;;
         --ranlib) OUTPUT="${ykllvm_bin_dir}/llvm-ranlib" ;;
+        --prelink-pipeline)
+            if [ -z "$2" ] || [ "$(echo $2 | cut -b 1,2)" = "--" ]; then
+                1>&2 echo "Error: Expected passes after --prelink-pipeline."
+                usage
+                exit 1
+            else
+                PRELINK_PASSES_STR=$2
+                shift
+            fi
+            ;;
+        --postlink-pipeline)
+            if [ -z "$2" ] || [ "$(echo $2 | cut -b 1,2)" = "--" ]; then
+                1>&2 echo "Error: Expected passes after --postlink-pipeline."
+                usage
+                exit 1
+            else
+                POSTLINK_PASSES_STR=$2
+                shift
+            fi
+            ;;
         --cflags)
             # Enable LTO.
             OUTPUT="${OUTPUT} -flto"
@@ -51,6 +72,9 @@ handle_arg() {
             # Without this, clang will slap `optnone` attributes on every
             # function, causing optimisations to skip them.
             OUTPUT="${OUTPUT} -Xclang -disable-O0-optnone"
+            if [ ! -z "${PRELINK_PASSES_STR}" ]; then
+                OUTPUT="${OUTPUT} -mllvm --newpm-passes=${PRELINK_PASSES_STR}"
+            fi
             case $mode in
                 debug) OUTPUT="$OUTPUT -g" ;;
             esac
@@ -111,7 +135,8 @@ handle_arg() {
             #
             # This pairs with `-Xclang -disable-O0-optnone`. See above.
             OUTPUT="${OUTPUT} -Wl,--mllvm=--yk-optnone-after-ir-passes"
-            OUTPUT="${OUTPUT} -Xlinker --lto-newpm-passes=${LINKTIME_PASSES}"
+
+            OUTPUT="${OUTPUT} -Xlinker --lto-newpm-passes=${POSTLINK_PASSES_STR}"
 
             # Have the `.llvmbc` and `.llvm_bb_addr_map` sections loaded into
             # memory by the loader.
@@ -171,8 +196,14 @@ mode=$1
 shift
 
 while [ $# -ne 0 ]; do
-    handle_arg $mode $1
-    shift
+    if [ -z "$2" ] || [ "$(echo $2 | cut -b 1,2)" = "--" ]; then
+        handle_arg $mode $1
+        shift
+    else
+        handle_arg $mode $1 $2
+        shift
+        shift
+    fi
 done
 
 echo ${OUTPUT}
